#!/bin/bash

set -euo pipefail

jarfile="assseq.jar"
defprogdir="/usr/share/assseq"
minjavamem="128M"
maxjavamem="1024M"
debug=0
version=0

function show_help () {
cat <<HEREDOC
File:

    `basename $0` - Launcher script for assseq.jar

Version:

    Wrapper script version 29 Jan 2018
    (to see assseq.jar version, use the '-v' option)

By:

    Anders.Larsson [at] icm.uu.se

Description:

    Assseq: a easy to use assembl.....
    a
    Citation: xxxxxxxxxxxxx
    http://dx.doi.org/1xxxxxxxxxxxxxx

    See http://ormbunkar.se/assseq for documentation
    and downloads.

    Source: https://github.com/andersla/Assseq

Options:

    -?, -h    -- show this help
    -d        -- show debug info in terminal
    -v        -- show assseq.jar version
    -x <size> -- set max mem size for java

Usage:

    `basename $0` infile
    `basename $0` infile1 infile2
    `basename $0` -x2048M infile
    `basename $0` -d infile
    `basename $0` -v
    `basename $0` -h

HEREDOC
}

#
# Adapted from stackoverflow-questions-59895
#
function resolve_links() {
  # parameters
  source="$1"
  # resolve $source until the file is no longer a symlink
  while [ -h "$source" ]; do
    dir="$(cd -P "$(dirname "$source")" && pwd)"
    # if $dir was a relative symlink, we need to resolve it relative to
    # the path where the symlink file was located
    source="$(readlink "$source")"
    [[ $dir != /* ]] && dir="$dir/$dir"
  done
  echo "$source"
}

## Check java
if type -p java &>/dev/null; then
    myjava=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    myjava="$JAVA_HOME/bin/java"
else
    "Error: Cannot locate java"
    exit 1
fi

## Check args
while getopts "h?vdx:" opt; do
    case "$opt" in
        h|\? )
            show_help
            exit 0
            ;;
        d )
            debug=1
            ;;
        v )
            version=1
            ;;
        x )
            maxjavamem=$OPTARG
            ;;
        * ) echo "Unrecognized argument. use '-h' for usage information."
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

## Set current directory default, and check if not in local
## then always use this jar - otherwise confusing
absolute_file="$(resolve_links $0)"
progdir=$(dirname $absolute_file)
assseq="$progdir/$jarfile"
if [ ! -f "$assseq" ]; then
    progdir="$defprogdir"
    assseq="$progdir/$jarfile"
    if [ ! -x "$assseq" ] ; then
        echo "$0: Error: Cannot find \'$progdir/$jarfile\'"
        echo "This script is just a wrapper for $jarfile."
        echo "See the assseq documentation for more information."
        exit 1
    fi
fi

## Try to get assseq version (experimental)
if [ "$version" -eq 1 ]; then
    nr=$("$myjava" -Djava.awt.headless=true -jar "$assseq" | grep -m1 'version' | awk '{print $NF}')
    echo "$jarfile v.$nr"
    exit 0
fi

## Launch assseq on all input
if [ $# -eq 0 ]; then
    if [ "$debug" -eq 0 ]; then
        $myjava -Xmx$maxjavamem -Xms$minjavamem -jar $assseq &> /dev/null &
    else
        $myjava -Xmx$maxjavamem -Xms$minjavamem -jar $assseq
    fi
else
    for fil in "$@" ; do
        if [ "$debug" -eq 0 ]; then
            $myjava -Xmx$maxjavamem -Xms$minjavamem -jar $assseq "$fil" &> /dev/null &
        else
            $myjava -Xmx$maxjavamem -Xms$minjavamem -jar $assseq "$fil" &
        fi
    done
fi

